export {
  hooks,
  CreateParallelHook,
  CreateWaterfallHook,
  EarlyHookResult,
  isEarlyHookResult,
  Hooks,
  Parallel,
  parallel,
  ParallelExec,
  parallelHook,
  waterfallHook,
  ParallelMiddleware,
  PluginHooks,
  pluginHooks,
  PluginOptions,
  TWaterfallRegister,
  WaterfallExec,
  Waterfall,
  waterfall,
  PluginRegisterInfo,
  TParallelRegister,
  WaterfallMiddleware,
} from 'plugin-hooks';
